### ISSUE TITLE
Proof of life

### ISSUE THREAD

**Issue by jaxley** [nitram509/jmacaroons#10]
Looks like this library may be the only available Java macaroon implementation?  But it's not actively maintained it seems.  Any plans to keep this going and maintain compatibility with the other implementations across languages?

**Comment by nitram509** [comment]
Hi Jason, indeed, I'm only looking occasionally into it. Fixing bugs (when reported, etc).
Every contribution is welcome, especially pull requests.
Besides that, I don't have an active roadmap nor further development plan.
