### ISSUE TITLE
Don't explicitly seed the SecureRandom instance

### ISSUE THREAD

**Issue by NeilMadden** [nitram509/jmacaroons#5]
The CryptoUtils class explicitly seeds the SecureRandom instance with the current time. This is a predictable source and so can only weaken the entropy. Let the underlying CSPRNG provider seed the SR itself. See https://www.veracode.com/blog/research/cryptographically-secure-pseudo-random-number-generator-csprng for a good recent write-up on this.

**Comment by nitram509** [comment]
Hi Neil,

thank you for pointing this out.
I've removed the explicit seeding of SecureRandom.

Regards
Martin
