### ISSUE TITLE
Non-constant time comparison of signatures

### ISSUE THREAD

**Issue by cstorey** [nitram509/jmacaroons#6]
In [MacaroonsVerifier](https://github.com/nitram509/jmacaroons/blob/046be89053bd8983300a4bf95d92faee3305a36e/src/main/java/com/github/nitram509/jmacaroons/MacaroonsVerifier.java#L101) it looks like the code uses `Arrays.equals` to compare the derived and provided signatures. Unfortunately, as mentioned in [A lesson in timing attacks](https://codahale.com/a-lesson-in-timing-attacks/), this is vulnerable.

**Comment by nitram509** [comment]
Thank you very much Ceri for spotting this.
I've committed a fix and will make it available, when next release is published.

Thank you.

Regards
Martin
