### ISSUE TITLE
Any plans for V2 Macaroon support

### ISSUE THREAD

**Issue by herrvendil** [nitram509/jmacaroons#7]
Hi

I use your project for parsing macaroons generated from an application that just switched to V2 Macaroons. Are there any plans for this project to support this in future?

Regards
Philip Vendil

**Comment by schmohlio** [comment]
I'm interested in helping

**Comment by nitram509** [comment]
Hi @herrvendil and @schmohlio,
as you might have already realized, I'm only looking occasionally into it. Fixing bugs (when reported, etc).
Every contribution is welcome, especially pull requests.
Besides that, I don't have an active roadmap nor further development plan.

**Comment by jaxley** [comment]
The fork https://github.com/nickrobison-usds/jmacaroons has already implemented support for v2 macaroons it seems.

**Comment by NeilMadden** [comment]
I've raised a PR that implements V2 binary format. (I didn't see the fork, but that appears to have only implement V2 JSON format from a quick glance).

**Comment by nitram509** [comment]
Hi everyone,

the V2 support was contributed by Neil Madden and I'm glad to say: has landed in MASTER branch already.
I hope to get the release ready quite soon, so you could all expect a proper release on maven central.

Regards
Martin

**Comment by michaelWuensch** [comment]
@nitram509 
Can you please just create a tag and do that release?
In my project I need V2. With the current master it works, but not with the latest 4.1 release.
Problem is if I opt in for snapshot by using implementation 'com.github.nitram509:jmacaroons:master-SNAPSHOT' it will kill reproducibility of the app as soon as anything in the master branch changes.

**Comment by nitram509** [comment]
@michaelWuensch  I did the 0.5 release and try to release on maven central as well

**Comment by nitram509** [comment]
@michaelWuensch v0.5.0 is released, see https://oss.sonatype.org/#nexus-search;quick~jmacaroons

**Comment by michaelWuensch** [comment]
@nitram509 Thank you sooo much for the release!
